Repository mnindrazaka/majer-otang, pull requests merged in 2022-09, with the labels that each got.

#40 integrate billing machine to billing form
  frontend/db.json
  frontend/src/containers/Billings/BillingForm.tsx
  frontend/src/containers/Billings/BillingForm__FirstStep.tsx
  frontend/src/containers/Billings/BillingForm__SecondStep.tsx
  frontend/src/containers/Billings/BillingList.tsx
  frontend/src/containers/Billings/BillingsPage.tsx
  frontend/src/machines/billings/billingMachine.ts
  frontend/src/machines/billings/mockFetcher.ts
Labels: FE

#41 Feat/create billing
  backend/core/module/billing-usecase.go
  backend/core/repository/biling-repository.go
  backend/core/repository/billing-member-repository.go
  backend/go.mod
  backend/handler/api/billing-handler.go
  backend/handler/api/request-builder.go
  backend/handler/api/response-builder.go
  backend/main.go
  backend/repository/billingMembers/repository.go
  backend/repository/billings/repository.go
Labels: BE

#46 feat: impelement update payment
  api.json
  backend/core/module/payment-usecase.go
  backend/core/repository/billing-member-repository.go
  backend/core/repository/payment-repository.go
  backend/handler/api/payment-handler.go
  backend/handler/api/payment-mapper.go
  backend/main.go
  backend/repository/billingMembers/repository.go
Labels: BE

#48 feat: integrate service to payment machine
  frontend/src/machines/paymentMachine.ts
  frontend/src/utils/fetcher.tsx
Labels: FE

#47 [feat] integrate billing machine to submit form
  frontend/server.js
  frontend/src/containers/Billings/BillingForm__FirstStep.tsx
  frontend/src/containers/Billings/BillingForm__SecondStep.tsx
  frontend/src/containers/Billings/BillingsPage.tsx
  frontend/src/containers/Billings/GeneralSuccess.tsx
  frontend/src/machines/billings/billingMachine.ts
Labels: FE

#51 feat: integrate payment machine to component
  frontend/db.json
  frontend/src/containers/MembersPage/MemberList.tsx
  frontend/src/containers/PaymentsPage/ConfirmationModal.tsx
  frontend/src/containers/PaymentsPage/PaymentList.tsx
  frontend/src/containers/PaymentsPage/PaymentsPage.tsx
  frontend/src/machines/paymentMachine.ts
  frontend/src/pages/payments/[memberId].tsx
Labels: FE

#49 feat: implement get payment by member id
  api.json
  backend/core/module/billing-usecase.go
  backend/core/module/payment-usecase.go
  backend/core/repository/biling-repository.go
  backend/core/repository/payment-repository.go
  backend/handler/api/payment-handler.go
  backend/handler/api/payment-mapper.go
  backend/main.go
  backend/repository/billings/repository.go
Labels: BE

#56 feat: add cors
  backend/handler/api/response-builder.go
Labels: BE

#59 bugfix: create billing
  backend/core/module/billing-usecase.go
  backend/handler/api/billing-handler.go
Labels: BE

#60 bugfix: allow methods (cors issue)
  backend/handler/api/response-builder.go
Labels: bug, BE

#55 feat: fixing is bill equally
  backend/core/module/billing-usecase.go
Labels: BE

#50 feat: update billing
  backend/api.json
  backend/core/module/billing-usecase.go
  backend/core/repository/biling-repository.go
  backend/core/repository/billing-member-repository.go
  backend/handler/api/billing-handler.go
  backend/handler/api/billing-mapper.go
  backend/main.go
  backend/repository/billingMembers/repository.go
  backend/repository/billings/repository.go
  backend/repository/members/repository.go
Labels: BE
