Repository mnindrazaka/majer-otang, pull requests merged in 2022-08, with the labels that each got.

#18 chore: init payment machine
  frontend/src/machines/paymentMachine.ts
Labels: FE

#19 fix json server port problem
  frontend/package.json
Labels: bug, FE

#25 Feat: billing list endpoint
  api.json
  backend/core/module/billing-usecase.go
  backend/core/repository/biling-repository.go
  backend/handler/api/billing-handler.go
  backend/handler/api/billing-mapper.go
  backend/handler/api/response-builder.go
  backend/main.go
  backend/repository/billing/repository.go
  backend/repository/members/repository.go
Labels: BE

#22 init machine service and integrate to billing page and form
  api.json
  frontend/db.json
  frontend/src/containers/Billings/BillingForm.tsx
  frontend/src/containers/Billings/BillingList.tsx
  frontend/src/containers/Billings/BillingsPage.tsx
  frontend/src/containers/Billings/GeneralError.tsx
  frontend/src/containers/Billings/GeneralLoading.tsx
  frontend/src/machines/billings/billingMachine.ts
  frontend/src/pages/_app.tsx
  frontend/src/utils/fetcher.tsx
Labels: FE

#16 Feat/get billing by
  api.json
  backend/core/module/billing-usecase.go
  backend/core/repository/biling-repository.go
  backend/core/repository/billing-member-repository.go
  backend/handler/api/billing-handler.go
  backend/handler/api/billing-mapper.go
  backend/main.go
  backend/repository/billingMembers/repository.go
  backend/repository/billings/repository.go
Labels: BE

#26 refactor billing machine with new action pattern
  frontend/src/containers/Billings/BillingsPage.tsx
  frontend/src/containers/Billings/GeneralError.tsx
  frontend/src/machines/billings/billingMachine.ts
Labels: FE

#23 chore: adding context and typing payment machine
  frontend/src/machines/paymentMachine.ts
Labels: FE
