Repository mnindrazaka/majer-otang, pull requests merged in 2022-10, with the labels that each got.

#82 bugfix: fixing billings response
  backend/core/module/billing-usecase.go
Labels: BE

#85 fix: use empty array when data member is null
  backend/core/module/member-usecase.go
Labels: BE

#86 fix: use empty array when data is null
  backend/core/module/payment-usecase.go
Labels: BE

#88 fix wrong endpoint path for get billig detail
  backend/api.json
Labels: FE, hacktoberfest

#89 fix: remove unused comments in code
  backend/core/module/billing-usecase.go
  backend/core/module/payment-usecase.go
  backend/main.go
  backend/repository/billingMembers/repository.go
  backend/repository/billings/repository.go
  backend/repository/members/repository.go
Labels: BE

#90 feat: add step to run project and generate entity from api json
  backend/README.md
Labels: BE

#91 ajdust billing list styling
  frontend/src/containers/Billings/BillingList.tsx
Labels: enhancement, FE, hacktoberfest

#92 fix: adding wrapper title page to be on the top
  frontend/src/containers/Billings/BillingList.tsx
  frontend/src/containers/MembersPage/MemberList.tsx
  frontend/src/containers/MembersPage/MembersPage.tsx
  frontend/src/containers/PaymentsPage/PaymentList.tsx
  frontend/src/containers/PaymentsPage/PaymentsPage.tsx
Labels: FE, hacktoberfest

#98 implement form validation on billing form
  frontend/src/containers/Billings/BillingForm__FirstStep.tsx
Labels: FE, hacktoberfest

#100 fix edit billing detail and header styling
  backend/api.json
  frontend/src/components/BottomMenu.tsx
  frontend/src/containers/Billings/BillingList.tsx
  frontend/src/containers/MembersPage/MembersPage.tsx
  frontend/src/containers/PaymentsPage/PaymentsPage.tsx
  frontend/src/machines/billings/billingMachine.ts
Labels: FE, hacktoberfest

#101 feat: adding price formatting on billing and payment list
  frontend/src/containers/Billings/BillingList.tsx
  frontend/src/containers/PaymentsPage/PaymentList.tsx
Labels: FE, hacktoberfest

#102 feat: adding eslint rules
  frontend/.eslintrc.json
  frontend/package.json
  frontend/src/components/BottomMenu.tsx
  frontend/src/containers/Billings/BillingForm__FirstStep.tsx
  frontend/src/containers/Billings/BillingForm__SecondStep.tsx
  frontend/src/containers/Billings/BillingList.tsx
  frontend/src/containers/Billings/BillingsPage.tsx
  frontend/src/containers/Billings/GeneralError.tsx
  frontend/src/containers/Billings/GeneralSuccess.tsx
  frontend/src/containers/MembersPage/MemberList.tsx
  frontend/src/containers/MembersPage/MembersPage.tsx
  frontend/src/containers/PaymentsPage/ConfirmationModal.tsx
  frontend/src/containers/PaymentsPage/PaymentList.tsx
  frontend/src/containers/PaymentsPage/PaymentsPage.tsx
  frontend/src/machines/billings/billingMachine.ts
  frontend/src/machines/paymentMachine.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/payments/[memberId].tsx
  frontend/src/utils/fetcher.tsx
  frontend/yarn.lock
Labels: FE, hacktoberfest

#103 fix: scroll on billing form second step
  frontend/src/containers/Billings/BillingForm__SecondStep.tsx
Labels: FE, hacktoberfest
